
export interface Collection {
  id: string;
  name: string;
  emoji: string;
  color: string;
}

export interface ErrorPattern {
  pattern: string;
  description: string;
  count: number;
  concepts: string[];
  probableCause: string;
  textReference: string;
  recommendedAction: {
    type: 'kurze Erklärung' | '3 gezielte Übungsfragen' | 'Erstellung von Karteikarten' | 'Start einer geführten Study-Session';
    reasoning: string;
  };
}

export interface LearningAnalysis {
  errorPatterns: ErrorPattern[];
  topThreeTypes: ErrorPattern[];
  overallHealth: string;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctAnswerIndices: number[];
  isMultipleChoice: boolean;
  explanation: string;
  distractorExplanations: string[];
  sourceReference: string;
  topic?: string;
  difficulty?: 'leicht' | 'mittel' | 'schwer';
  learningGoal?: string;
}

export interface Flashcard {
  id: string;
  front: string;
  back: string;
  level: number;
  nextReview: number;
  lastInterval?: number;
}

export interface FlashcardDeck {
  id: string;
  title: string;
  cards: Flashcard[];
  sourceDocumentId?: string;
}

export interface ProcessedDocument {
  id: string;
  name: string;
  content: string;        // base64 (PDF) oder extrahierter Text; leer wenn PDF aus Storage noch nicht geladen
  type: 'pdf' | 'text' | 'docx';
  uploadDate: number;
  collectionId?: string;
  storagePath?: string;   // gesetzt wenn PDF in Supabase Storage liegt
}

export interface TopicMetric {
  id: string;
  topic: string;
  subject?: string;
  confidence: number;
  lastReviewed: number;
  totalAttempts: number;
  correctAttempts: number;
}

export enum ActiveTab {
  DASHBOARD = 'DASHBOARD',
  LIBRARY = 'LIBRARY',
  QUIZ = 'QUIZ',
  CARDS = 'CARDS',
  SEARCH = 'SEARCH',
  PLANNER = 'PLANNER',
  PAPER = 'PAPER',
  RADAR = 'RADAR',
  EXPLAINER = 'EXPLAINER',
  EXAM = 'EXAM',
  RECALL = 'RECALL'
}

export enum QuizType {
  FAST = 'FAST',
  INTENSIVE = 'INTENSIVE',
  CUSTOM = 'CUSTOM'
}

export interface UserAnswer {
  questionIndex: number;
  selectedOptionIndices: number[];
  isCorrect: boolean;
}

export interface SearchResult {
  title: string;
  authors: string;
  year: string;
  url: string;
  apaCitation: string;
  snippet: string;
  journal?: string;
  doi?: string;
  abstract?: string;
  openalex_id?: string;
  doi_url?: string;
}

export interface PaperOutlineSection {
  title: string;
  description: string;
}

export interface AcademicSource extends SearchResult {
  id: string;
  type: 'article' | 'book' | 'other';
}

export type CitationStyle = 'APA' | 'MLA' | 'Harvard' | 'Chicago';

export interface MultiStyleCitation {
  apa: { entry: string; inTextKlammer: string; inTextNarrativ: string };
  mla: { entry: string; inText: string };
  harvard: { entry: string; inText: string; direct: string };
  chicago: { fullNote: string; shortNote: string; bibliography: string };
}

export interface StudyEntry {
  id: string;
  day: string;
  subject: string;
  topic: string;
  startTime: string;
  endTime: string;
  completed: boolean;
  color?: string;
  isAutoGenerated?: boolean;
}

export interface ExamTerm {
  id: string;
  title: string;
  date: string;
  topics: string[];
}

export interface ExamQuestion {
  id: string;
  question: string;
  type: 'mc' | 'open';
  options?: string[];
  solution: string;
  points: number;
  userAnswer?: string | number[];
  feedback?: string;
  achievedPoints?: number;
}

// --- Recall Types ---
export interface RecallChallenge {
  question: string;
  expectedKeywords: string[];
  conceptContext: string;
}

export interface RecallEvaluation {
  score: number; // 0-100
  feedback: string;
  missingPoints: string[];
  strengths: string[];
  suggestedReview: string;
}

// --- Orchestrator Types ---

export interface NextAction {
  title: string;
  module: 'analyse' | 'quiz' | 'cards' | 'explain' | 'calendar' | 'exam';
  timebox_minutes: 5 | 10 | 15 | 25 | 45;
  focus_topics: string[];
  why: string;
}

export interface CalendarSuggestion {
  should_schedule: boolean;
  suggested_blocks: {
    day: string;
    start_time: string;
    duration_minutes: number;
    module: string;
    focus_topics: string[];
  }[];
}

export interface LearningFlowResult {
  updated_radar: {
    topic: string;
    status: 'schwach' | 'mittel' | 'stabil';
    priority: number;
    reason: string;
  }[];
  next_actions: NextAction[];
  calendar_suggestion: CalendarSuggestion;
  blocking_questions: { question: string; needed_field: string }[];
}

