import type { FlashcardDeck, ExamTerm, StudyEvent } from '../types';
import type { MistakeItem } from './mistakeReviewService';
import { migrateLegacyCard } from './spacedRepetition';

/**
 * spacedPlanningService — Opt-in-Automatik für den StudyPlanner.
 *
 * Platziert Wiederholungs-Sessions zeitversetzt (Spacing-Effekt) als klar
 * markierte Auto-Events (type 'review', isAutoGenerated). Deterministisch:
 * gleiche Eingaben → gleicher Plan mit gleichen IDs, dadurch idempotente
 * Regeneration und konvergenter Cloud-Sync. Manuelle Einträge werden NIE
 * verschoben oder verändert.
 */

export const SPACED_PLANNING_KEY = 'quizwise_spaced_planning';

export interface SpacedPlanningSettings {
  enabled: boolean;
  /** Letzter Tag (YYYY-MM-DD), an dem der Plan regeneriert wurde. */
  lastRunDay: string | null;
}

export const getSpacedSettings = (): SpacedPlanningSettings => {
  try {
    const raw = localStorage.getItem(SPACED_PLANNING_KEY);
    if (raw) return JSON.parse(raw);
  } catch {}
  return { enabled: false, lastRunDay: null };
};

export const saveSpacedSettings = (settings: SpacedPlanningSettings, userId?: string | null): void => {
  try { localStorage.setItem(SPACED_PLANNING_KEY, JSON.stringify(settings)); } catch {}
  if (userId) {
    import('./syncService').then(({ syncPreferences }) => syncPreferences(userId, { spaced_planning: settings.enabled })).catch(() => {});
  }
};

// ─── Datums-Helfer (lokale Zeitzone, nie toISOString) ────────────────────────

const DAY_MS = 24 * 60 * 60 * 1000;

export function toDateStr(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

const startOfDay = (d: Date): Date => new Date(d.getFullYear(), d.getMonth(), d.getDate());
const addDays = (d: Date, n: number): Date => new Date(d.getFullYear(), d.getMonth(), d.getDate() + n);

const slug = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9äöüß]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 24) || 'x';

// ─── Fällig-Prognose ──────────────────────────────────────────────────────────

/**
 * Fällige Karten + Fehlerfragen pro Tag, Index 0 = heute.
 * Überfällige zählen auf Tag 0.
 */
export function buildDueForecast(
  decks: FlashcardDeck[],
  mistakes: MistakeItem[],
  days = 14,
  now: Date = new Date()
): number[] {
  const counts = new Array<number>(days).fill(0);
  const today0 = startOfDay(now).getTime();

  const dueTimes: number[] = [
    ...decks.flatMap(d => d.cards.map(c => (c.srs ?? migrateLegacyCard(c)).nextReview)),
    ...mistakes.map(m => m.srs.nextReview),
  ];

  for (const t of dueTimes) {
    const dayIdx = Math.max(0, Math.floor((t - today0) / DAY_MS));
    if (dayIdx < days) counts[dayIdx] += 1;
  }
  return counts;
}

// ─── Plan-Generierung ─────────────────────────────────────────────────────────

const MAX_AUTO_PER_DAY = 2;
const MAX_TOTAL_PER_DAY = 3;
const MAX_SHIFT_DAYS = 3;
const LEARN_SEED_WINDOW_DAYS = 3;
const LEARN_INTERVALS = [1, 3, 7];
const EXAM_OFFSETS = [-7, -3, -1];
const EXAM_HORIZON_DAYS = 30;
const DUE_LOAD_THRESHOLD = 5;
const FORECAST_DAYS = 14;

export interface SpacedPlanInput {
  decks: FlashcardDeck[];
  mistakes: MistakeItem[];
  examTerms: ExamTerm[];
  /** Manuelle Events + sonstige Belegung zur Kollisionsvermeidung. */
  existingEvents: StudyEvent[];
  /** Letzte Quiz-Sessions (dedupe passiert intern), z.B. aus quizHistoryService. */
  recentQuizzes: { docName: string; timestamp: number }[];
  today?: Date;
}

interface Candidate {
  id: string;
  title: string;
  targetDate: Date;
  sourceKind: 'topic' | 'exam' | 'due';
  intervalStep?: number;
  /** Auto-Events zu einer Klausur dürfen nie auf/nach dem Klausurtag liegen. */
  notOnOrAfter?: string;
}

/** Gibt NUR Auto-Events zurück (type 'review', isAutoGenerated, stabile IDs). */
export function buildSpacedPlan(input: SpacedPlanInput): StudyEvent[] {
  const today = startOfDay(input.today ?? new Date());

  // Belegung pro Tag: manuelle Events + Klausurtermine
  const totalPerDay = new Map<string, number>();
  const bump = (map: Map<string, number>, key: string) => map.set(key, (map.get(key) ?? 0) + 1);
  for (const ev of input.existingEvents) {
    if (!ev.isAutoGenerated) bump(totalPerDay, ev.date);
  }
  for (const exam of input.examTerms) bump(totalPerDay, exam.date);

  const candidates: Candidate[] = [];

  // 1. Klausur-Anker: −7/−3/−1 Tage vor jeder Klausur in <= 30 Tagen
  for (const exam of input.examTerms) {
    const examDate = new Date(exam.date + 'T12:00:00');
    if (isNaN(examDate.getTime())) continue;
    const examDay = startOfDay(examDate);
    const daysUntil = Math.round((examDay.getTime() - today.getTime()) / DAY_MS);
    if (daysUntil <= 0 || daysUntil > EXAM_HORIZON_DAYS) continue;
    for (const offset of EXAM_OFFSETS) {
      const target = addDays(examDay, offset);
      if (target < today) continue;
      candidates.push({
        id: `auto-exam-${slug(exam.title)}-o${Math.abs(offset)}`,
        title: `Klausur-Wiederholung: ${exam.title}`,
        targetDate: target,
        sourceKind: 'exam',
        notOnOrAfter: toDateStr(examDay),
      });
    }
  }

  // 2. Lern-Seeds: pro Doc mit Quiz in den letzten 3 Tagen → +1/+3/+7
  const newestByDoc = new Map<string, number>();
  for (const q of input.recentQuizzes) {
    if (!q.docName) continue;
    const prev = newestByDoc.get(q.docName);
    if (prev === undefined || q.timestamp > prev) newestByDoc.set(q.docName, q.timestamp);
  }
  for (const [docName, ts] of newestByDoc) {
    const quizDay = startOfDay(new Date(ts));
    const age = Math.round((today.getTime() - quizDay.getTime()) / DAY_MS);
    if (age < 0 || age > LEARN_SEED_WINDOW_DAYS) continue;
    for (const step of LEARN_INTERVALS) {
      const target = addDays(quizDay, step);
      if (target <= today) continue; // Vergangenheit/heute überspringen
      candidates.push({
        id: `auto-topic-${slug(docName)}-s${step}`,
        title: `Wiederholen: ${docName}`,
        targetDate: target,
        sourceKind: 'topic',
        intervalStep: step,
      });
    }
  }

  // 3. Fällig-Last: Tage mit >= 5 fälligen Items ohne anderes Auto-Event
  const forecast = buildDueForecast(input.decks, input.mistakes, FORECAST_DAYS, today);
  for (let i = 1; i < FORECAST_DAYS; i++) { // ab morgen — heute erledigt das Tages-Review
    if (forecast[i] < DUE_LOAD_THRESHOLD) continue;
    candidates.push({
      id: `auto-due-d${i}`,
      title: `Fällige Wiederholungen (${forecast[i]})`,
      targetDate: addDays(today, i),
      sourceKind: 'due',
    });
  }

  // Deterministische Reihenfolge: Klausur vor Lern-Seed vor Fällig-Last, dann Datum, dann ID
  const kindRank = { exam: 0, topic: 1, due: 2 } as const;
  candidates.sort((a, b) =>
    kindRank[a.sourceKind] - kindRank[b.sourceKind]
    || a.targetDate.getTime() - b.targetDate.getTime()
    || a.id.localeCompare(b.id)
  );

  // Platzierung mit Staffelung: max 2 Auto/Tag, max 3 gesamt/Tag; volle Tage → +1 (max +3)
  const autoPerDay = new Map<string, number>();
  const plan: StudyEvent[] = [];

  for (const cand of candidates) {
    let placed: string | null = null;
    for (let shift = 0; shift <= MAX_SHIFT_DAYS; shift++) {
      const day = addDays(cand.targetDate, shift);
      const dayStr = toDateStr(day);
      // Kandidaten starten nie vor heute (Filter oben), Shifts gehen nur vorwärts
      if (cand.notOnOrAfter && dayStr >= cand.notOnOrAfter) break; // nichts auf/nach der Klausur
      const autoCount = autoPerDay.get(dayStr) ?? 0;
      const totalCount = (totalPerDay.get(dayStr) ?? 0) + autoCount;
      const dayFree = cand.sourceKind === 'due'
        ? autoCount === 0 && totalCount < MAX_TOTAL_PER_DAY
        : autoCount < MAX_AUTO_PER_DAY && totalCount < MAX_TOTAL_PER_DAY;
      if (dayFree) { placed = dayStr; break; }
    }
    if (!placed) continue; // kein Platz in +3 Tagen → verwerfen

    bump(autoPerDay, placed);
    plan.push({
      id: `${cand.id}-${placed}`,
      title: cand.title,
      date: placed,
      type: 'review',
      description: 'Automatisch geplant (Spaced Repetition)',
      isAutoGenerated: true,
      sourceKind: cand.sourceKind,
      ...(cand.intervalStep !== undefined ? { intervalStep: cand.intervalStep } : {}),
    });
  }

  return plan;
}

/** Ersetzt alle Auto-Events durch den neuen Plan; manuelle Events bleiben exakt unverändert. */
export function applySpacedPlan(events: StudyEvent[], plan: StudyEvent[]): StudyEvent[] {
  return [...events.filter(e => !e.isAutoGenerated), ...plan];
}
