import { describe, it, expect, beforeEach } from 'vitest';
import type { FlashcardDeck, ExamTerm, StudyEvent } from '../types';
import { buildDueForecast, buildSpacedPlan, applySpacedPlan, toDateStr, getSpacedSettings, saveSpacedSettings } from './spacedPlanningService';
import { createSrsState } from './spacedRepetition';
import type { MistakeItem } from './mistakeReviewService';

// Fixes Referenzdatum für deterministische Tests (Mittwoch)
const TODAY = new Date(2026, 6, 15); // 15.07.2026
const dayStr = (offset: number) => toDateStr(new Date(2026, 6, 15 + offset));

const mkDeck = (dueOffsets: number[]): FlashcardDeck => ({
  id: 'd1', title: 'Deck',
  cards: dueOffsets.map((off, i) => ({
    id: `c${i}`, front: 'f', back: 'b', level: 1, nextReview: 0,
    srs: { ...createSrsState(), nextReview: TODAY.getTime() + off * 86400000 },
  })),
});

const mkMistake = (dueOffset: number): MistakeItem => ({
  id: 'm1',
  question: { question: 'Q', options: [], correctAnswerIndices: [], isMultipleChoice: false, explanation: '', distractorExplanations: [], sourceReference: '' },
  docId: 'doc', docName: 'Doc', addedAt: 0, lapses: 0,
  srs: { ...createSrsState(), nextReview: TODAY.getTime() + dueOffset * 86400000 },
});

const baseInput = {
  decks: [] as FlashcardDeck[],
  mistakes: [] as MistakeItem[],
  examTerms: [] as ExamTerm[],
  existingEvents: [] as StudyEvent[],
  recentQuizzes: [] as { docName: string; timestamp: number }[],
  today: TODAY,
};

describe('buildDueForecast', () => {
  it('zählt Überfällige auf Tag 0', () => {
    const forecast = buildDueForecast([mkDeck([-3, -1, 0])], [], 7, TODAY);
    expect(forecast[0]).toBe(3);
  });

  it('verteilt zukünftige Fälligkeiten auf die richtigen Tage', () => {
    const forecast = buildDueForecast([mkDeck([1, 1, 3])], [mkMistake(3)], 7, TODAY);
    expect(forecast[1]).toBe(2);
    expect(forecast[3]).toBe(2);
  });
});

describe('buildSpacedPlan', () => {
  it('Lern-Seeds: Quiz heute → Events an +1/+3/+7', () => {
    const plan = buildSpacedPlan({ ...baseInput, recentQuizzes: [{ docName: 'Statistik', timestamp: TODAY.getTime() }] });
    const dates = plan.filter(e => e.sourceKind === 'topic').map(e => e.date).sort();
    expect(dates).toEqual([dayStr(1), dayStr(3), dayStr(7)]);
    expect(plan.every(e => e.isAutoGenerated && e.type === 'review')).toBe(true);
  });

  it('Lern-Seeds: vergangene Intervalle werden übersprungen', () => {
    // Quiz vor 2 Tagen → +1 liegt in der Vergangenheit → nur +3 (=+1 ab heute) und +7
    const plan = buildSpacedPlan({ ...baseInput, recentQuizzes: [{ docName: 'Bio', timestamp: TODAY.getTime() - 2 * 86400000 }] });
    const steps = plan.map(e => e.intervalStep).sort();
    expect(steps).toEqual([3, 7]);
  });

  it('Klausur-Anker: Events an -7/-3/-1, nichts auf/nach dem Klausurtag', () => {
    const exam: ExamTerm = { id: 'e1', title: 'Statistik Klausur', date: dayStr(10), topics: [] };
    const plan = buildSpacedPlan({ ...baseInput, examTerms: [exam] });
    const dates = plan.map(e => e.date).sort();
    expect(dates).toEqual([dayStr(3), dayStr(7), dayStr(9)]);
    expect(plan.every(e => e.date < exam.date)).toBe(true);
  });

  it('Klausuren weiter als 30 Tage entfernt werden ignoriert', () => {
    const plan = buildSpacedPlan({ ...baseInput, examTerms: [{ id: 'e1', title: 'Fern', date: dayStr(45), topics: [] }] });
    expect(plan).toHaveLength(0);
  });

  it('Fällig-Last: Tag mit >= 5 fälligen Items bekommt Event (ab morgen)', () => {
    const plan = buildSpacedPlan({ ...baseInput, decks: [mkDeck([2, 2, 2, 2, 2])] });
    expect(plan).toHaveLength(1);
    expect(plan[0].date).toBe(dayStr(2));
    expect(plan[0].sourceKind).toBe('due');
    expect(plan[0].title).toContain('5');
  });

  it('max. 2 Auto-Events pro Tag — Überschuss wird verschoben', () => {
    // 3 Docs mit Quiz heute → 3x "+1" am selben Tag → einer rutscht auf +2
    const plan = buildSpacedPlan({
      ...baseInput,
      recentQuizzes: [
        { docName: 'A', timestamp: TODAY.getTime() },
        { docName: 'B', timestamp: TODAY.getTime() },
        { docName: 'C', timestamp: TODAY.getTime() },
      ],
    });
    const day1Count = plan.filter(e => e.date === dayStr(1)).length;
    expect(day1Count).toBe(2);
    expect(plan.filter(e => e.date === dayStr(2)).length).toBeGreaterThanOrEqual(1);
  });

  it('voller Tag (manuelle Events + Klausur) → Auto-Event weicht aus', () => {
    const manual: StudyEvent[] = [
      { id: 'm1', title: 'Arzt', date: dayStr(1), type: 'reminder' },
      { id: 'm2', title: 'Lernen', date: dayStr(1), type: 'study' },
      { id: 'm3', title: 'Sport', date: dayStr(1), type: 'reminder' },
    ];
    const plan = buildSpacedPlan({ ...baseInput, existingEvents: manual, recentQuizzes: [{ docName: 'A', timestamp: TODAY.getTime() }] });
    expect(plan.filter(e => e.date === dayStr(1))).toHaveLength(0);
    expect(plan.some(e => e.date === dayStr(2))).toBe(true);
  });

  it('Regeneration ist idempotent (identische IDs)', () => {
    const input = {
      ...baseInput,
      recentQuizzes: [{ docName: 'Statistik', timestamp: TODAY.getTime() }],
      examTerms: [{ id: 'e1', title: 'Klausur', date: dayStr(12), topics: [] }],
      decks: [mkDeck([2, 2, 2, 2, 2])],
    };
    const a = buildSpacedPlan(input);
    const b = buildSpacedPlan(input);
    expect(a).toEqual(b);
    expect(new Set(a.map(e => e.id)).size).toBe(a.length);
  });
});

describe('applySpacedPlan', () => {
  it('lässt manuelle Events exakt unverändert und ersetzt Auto-Events', () => {
    const manual: StudyEvent = { id: 'm1', title: 'Arzt', date: dayStr(1), type: 'reminder' };
    const oldAuto: StudyEvent = { id: 'auto-x', title: 'Alt', date: dayStr(2), type: 'review', isAutoGenerated: true };
    const newAuto: StudyEvent = { id: 'auto-y', title: 'Neu', date: dayStr(3), type: 'review', isAutoGenerated: true };
    const result = applySpacedPlan([manual, oldAuto], [newAuto]);
    expect(result).toEqual([manual, newAuto]);
  });
});

describe('Settings', () => {
  beforeEach(() => localStorage.clear());

  it('Default: disabled', () => {
    expect(getSpacedSettings()).toEqual({ enabled: false, lastRunDay: null });
  });

  it('Roundtrip', () => {
    saveSpacedSettings({ enabled: true, lastRunDay: '2026-07-15' });
    expect(getSpacedSettings()).toEqual({ enabled: true, lastRunDay: '2026-07-15' });
  });
});
