
import React, { useState, useMemo } from 'react';
import { ActiveTab, LearningFlowResult, StudyEntry } from '../types';
import { GeneratedImage } from './GeneratedImage';
import { toast } from '../services/toast';

const USAGE_KEY = 'quizwise_feature_usage';

function getUsageCounts(): Record<string, number> {
  try {
    return JSON.parse(localStorage.getItem(USAGE_KEY) || '{}');
  } catch {
    return {};
  }
}

function trackUsage(id: ActiveTab) {
  const counts = getUsageCounts();
  counts[id] = (counts[id] || 0) + 1;
  localStorage.setItem(USAGE_KEY, JSON.stringify(counts));
}

interface DashboardProps {
  onTabChange: (tab: ActiveTab) => void;
  flowResult: LearningFlowResult | null;
  onAcceptFlow: (res: LearningFlowResult) => void;
}

interface ActionCard {
  id: ActiveTab;
  title: string;
  desc: string;
  prompt: string;
  color: string;
  badge?: string;
}

const BASE_CARDS: ActionCard[] = [
  { id: ActiveTab.RECALL, title: 'Recall Studio', desc: 'Meistere Themen mit der Feynman-Methode.', prompt: 'Human brain active recall, academic illustration', color: 'text-indigo-600', badge: 'Active Recall' },
  { id: ActiveTab.LIBRARY, title: 'Bibliothek', desc: 'Verwalte deine PDF-Sammlung und Quellen.', prompt: 'Academic library books, minimalist illustration', color: 'text-blue-500' },
  { id: ActiveTab.QUIZ, title: 'Quiz Center', desc: 'KI-gestützte Tests für maximalen Erfolg.', prompt: 'Target bullseye icon, academic minimalist illustration', color: 'text-indigo-500', badge: 'KI-Powered' },
  { id: ActiveTab.EXAM, title: 'Klausur-Modus', desc: 'Simuliere echte Prüfungen unter Zeitdruck.', prompt: 'Exam paper graduation cap, academic illustration', color: 'text-rose-500', badge: 'Advanced' },
  { id: ActiveTab.CARDS, title: 'Karteikarten', desc: 'Training nach Anki-Standard.', prompt: 'Flashcards study deck, minimalist illustration', color: 'text-violet-500' },
  { id: ActiveTab.RADAR, title: 'Lern-Analyse', desc: 'Identifiziere Lücken im Verständnis.', prompt: 'Data analysis radar chart, academic illustration', color: 'text-emerald-500' }
];

export const Dashboard: React.FC<DashboardProps> = ({ onTabChange, flowResult }) => {
  const [hovered, setHovered] = useState<ActiveTab | null>(null);
  const [usageCounts, setUsageCounts] = useState<Record<string, number>>(getUsageCounts);

  const cards = useMemo(() => {
    return [...BASE_CARDS].sort((a, b) => (usageCounts[b.id] || 0) - (usageCounts[a.id] || 0));
  }, [usageCounts]);

  const handleCardClick = (id: ActiveTab) => {
    trackUsage(id);
    setUsageCounts(getUsageCounts());
    onTabChange(id);
  };

  const handleAcceptSuggestion = (suggestion: any) => {
    const plan = JSON.parse(localStorage.getItem('study_plan') || '[]');
    const newEntry: StudyEntry = {
      id: Math.random().toString(36).substr(2, 9),
      day: suggestion.day,
      startTime: suggestion.start_time,
      endTime: "12:00",
      subject: suggestion.module,
      topic: suggestion.focus_topics.join(', '),
      completed: false,
      isAutoGenerated: true,
      color: 'indigo'
    };
    localStorage.setItem('study_plan', JSON.stringify([...plan, newEntry]));
    toast.success('Im Lernplan eingetragen!');
    onTabChange(ActiveTab.PLANNER);
  };

  return (
    <div className="space-y-12 lg:space-y-24 py-12 px-4 animate-in fade-in duration-1000">
      {/* Hero Section */}
      <div className="text-center space-y-6">
        <div className="space-y-2">
            <h1 className="text-7xl sm:text-8xl lg:text-9xl font-light tracking-tighter text-slate-900 dark:text-white leading-none">
                Quiz<span className="font-bold text-indigo-500">Wise</span>
            </h1>
            <p className="text-[10px] sm:text-xs font-black uppercase tracking-[1em] text-slate-400 dark:text-white/30 pl-4">
                Advanced Academic Intelligence
            </p>
        </div>
      </div>

      {/* Intelligence Insights */}
      {flowResult && (
        <div className="max-w-6xl mx-auto space-y-8 animate-in slide-in-from-bottom-8 duration-700">
          <div className="flex justify-between items-center px-4">
            <h2 className="text-[11px] font-black uppercase tracking-[0.4em] text-indigo-500 flex items-center gap-2">
              Nächste Schritte (KI-Empfehlung)
              <GeneratedImage prompt="Sparkles icon, academic minimalist" className="w-4 h-4 rounded-full" />
            </h2>
          </div>
          
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {flowResult.next_actions.map((action, i) => (
              <button 
                key={i}
                onClick={() => onTabChange(action.module.toUpperCase() as ActiveTab)}
                className="bg-indigo-600 p-8 rounded-[32px] text-white text-left shadow-3d-deep hover:scale-105 transition-all group overflow-hidden relative"
              >
                <div className="absolute top-0 right-0 w-24 h-24 bg-white/5 blur-2xl rounded-full translate-x-8 -translate-y-8"></div>
                <div className="relative z-10 space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-[9px] font-black uppercase tracking-widest opacity-60">{action.timebox_minutes} Min. Fokus</span>
                    <span className="text-xs">➔</span>
                  </div>
                  <h3 className="text-xl font-black leading-tight">{action.title}</h3>
                  <p className="text-[11px] font-medium opacity-80 italic">"{action.why}"</p>
                </div>
              </button>
            ))}

            {flowResult.calendar_suggestion.should_schedule && flowResult.calendar_suggestion.suggested_blocks.map((block, i) => (
               <div key={i} className="p-8 rounded-[32px] flex flex-col justify-between group border-2 border-dashed border-indigo-200 dark:border-indigo-900" style={{ background: 'var(--bg-sidebar)' }}>
                  <div>
                    <span className="text-[9px] font-black uppercase text-indigo-500 tracking-widest mb-2 block">Lernplan-Vorschlag</span>
                    <h3 className="text-lg font-black dark:text-white">{block.day}, {block.start_time} Uhr</h3>
                    <p className="text-[11px] text-slate-500 mt-1">{block.focus_topics.join(', ')}</p>
                  </div>
                  <button 
                    onClick={() => handleAcceptSuggestion(block)}
                    className="mt-6 w-full py-3 bg-slate-50 dark:bg-slate-800 text-[10px] font-black uppercase tracking-widest rounded-xl hover:bg-indigo-600 hover:text-white transition-all"
                  >In Kalender eintragen</button>
               </div>
            ))}
          </div>
        </div>
      )}

      {/* Standard Navigation Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8 max-w-6xl mx-auto w-full">
        {cards.map((card) => {
          const isHovered = hovered === card.id;
          return (
            <button
              key={card.id}
              onClick={() => handleCardClick(card.id)}
              onMouseEnter={() => setHovered(card.id)}
              onMouseLeave={() => setHovered(null)}
              className="group relative rounded-[32px] lg:rounded-[48px] p-8 lg:p-12 text-left shadow-3d-raised hover:shadow-3d-deep hover:-translate-y-2 transition-all duration-300 overflow-hidden active:scale-[0.98]"
              style={isHovered
                ? { background: 'var(--primary)', border: '1px solid var(--primary)', boxShadow: '0 20px 40px color-mix(in srgb, var(--primary) 35%, transparent)' }
                : { background: 'var(--bg-sidebar)', border: '1px solid var(--border-color)' }
              }
            >
              <div className="absolute top-0 right-0 w-40 h-40 rounded-full blur-3xl transition-opacity duration-300 pointer-events-none"
                style={{ background: isHovered ? 'rgba(255,255,255,0.15)' : 'transparent', opacity: isHovered ? 1 : 0 }}
              />
              <div className="relative z-10 space-y-6">
                <div className="flex justify-between items-start">
                  <div
                    className="w-12 h-12 lg:w-16 lg:h-16 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-all duration-300"
                    style={isHovered
                      ? { background: 'rgba(255,255,255,0.2)', color: 'var(--primary-text)' }
                      : { background: 'color-mix(in srgb, var(--primary) 12%, var(--bg-sidebar))', color: 'var(--primary)' }
                    }
                  >
                    <GeneratedImage prompt={card.prompt} className="w-7 h-7 lg:w-9 lg:h-9" />
                  </div>
                  {card.badge && (
                    <span
                      className="text-[9px] font-black uppercase tracking-widest px-3 py-1.5 rounded-full transition-colors duration-300"
                      style={isHovered
                        ? { background: 'rgba(255,255,255,0.2)', color: 'var(--primary-text)', border: '1px solid rgba(255,255,255,0.3)' }
                        : { background: 'var(--p50)', color: 'var(--primary)', border: '1px solid var(--p100)' }
                      }
                    >
                      {card.badge}
                    </span>
                  )}
                </div>
                <div className="space-y-2">
                  <h3
                    className="text-2xl lg:text-3xl font-black tracking-tight transition-colors duration-300"
                    style={{ color: isHovered ? 'var(--primary-text)' : undefined }}
                  >
                    {card.title}
                  </h3>
                  <p
                    className="text-sm lg:text-base leading-relaxed font-medium transition-colors duration-300"
                    style={{ color: isHovered ? 'color-mix(in srgb, var(--primary-text) 75%, transparent)' : undefined }}
                  >
                    {card.desc}
                  </p>
                </div>
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
};
