
import React, { useState, useMemo } from 'react';
import type { User } from '@supabase/supabase-js';
import { ActiveTab, LearningFlowResult, StudyEntry, FlashcardDeck, ProcessedDocument } from '../types';
import { AgentChat } from './AgentChat';
import { toast } from '../services/toast';
import {
  Bot, Layers, Flame, Brain, HelpCircle, GraduationCap,
  Play, ArrowRight, Calendar,
} from 'lucide-react';
import { countDueCards, migrateLegacyCard } from '../services/spacedRepetition';
import { getStreak } from '../services/streakService';

interface DashboardProps {
  onTabChange: (tab: ActiveTab) => void;
  flowResult: LearningFlowResult | null;
  onAcceptFlow: (res: LearningFlowResult) => void;
  documents?: ProcessedDocument[];
  user?: User | null;
}

const MODES = [
  { tab: ActiveTab.RECALL, label: 'Erklären üben', hint: 'Feynman-Methode',    Icon: Brain },
  { tab: ActiveTab.QUIZ,   label: 'Quiz',           hint: 'Fragen aus Unterlagen', Icon: HelpCircle },
  { tab: ActiveTab.EXAM,   label: 'Klausur üben',   hint: 'Prüfung simulieren', Icon: GraduationCap },
] as const;

export const Dashboard: React.FC<DashboardProps> = ({
  onTabChange, flowResult, documents = [], user,
}) => {
  const [coachOpen, setCoachOpen] = useState(false);

  const firstName = useMemo(() => {
    const full = user?.user_metadata?.full_name as string | undefined;
    if (full) return full.split(' ')[0];
    const email = user?.email;
    if (email) return email.split('@')[0];
    return 'dich';
  }, [user]);

  const dueCardsCount = useMemo(() => {
    try {
      const decks: FlashcardDeck[] = JSON.parse(localStorage.getItem('flashcard_decks') || '[]');
      const allCards = decks.flatMap(d =>
        d.cards.map(c => (c.srs ? c : { ...c, srs: migrateLegacyCard(c) }))
      );
      return countDueCards(allCards);
    } catch { return 0; }
  }, []);

  const streak = useMemo(() => getStreak(), []);
  const estMinutes = Math.max(5, Math.ceil(dueCardsCount * 2.5));

  const weiterlernCard = useMemo(() => {
    try {
      const raw = localStorage.getItem('quizwise_quiz_progress');
      if (raw) {
        const { meta, timestamp } = JSON.parse(raw);
        if (meta && timestamp && Date.now() - timestamp < 7 * 24 * 60 * 60 * 1000) {
          return { label: meta.docName || 'Quiz fortsetzen', tab: ActiveTab.QUIZ };
        }
      }
    } catch {}
    try {
      const decks: FlashcardDeck[] = JSON.parse(localStorage.getItem('flashcard_decks') || '[]');
      if (decks.length > 0) return { label: decks[decks.length - 1].title, tab: ActiveTab.CARDS };
    } catch {}
    return null;
  }, []);

  const nextExam = useMemo(() => {
    try {
      const terms: Array<{ date: string; subject: string }> = JSON.parse(
        localStorage.getItem('quizwise_exam_terms') || '[]'
      );
      const future = terms
        .map(t => ({ ...t, ms: new Date(t.date).getTime() }))
        .filter(t => t.ms > Date.now())
        .sort((a, b) => a.ms - b.ms);
      if (!future.length) return null;
      const days = Math.ceil((future[0].ms - Date.now()) / (1000 * 60 * 60 * 24));
      return { subject: future[0].subject, days };
    } catch { return null; }
  }, []);

  const coachContext = useMemo(() => {
    try {
      const metrics = JSON.parse(localStorage.getItem('quizwise_metrics') || '[]');
      const examTerms = JSON.parse(localStorage.getItem('quizwise_exam_terms') || '[]');
      return { metrics, examTerms, currentTab: 'DASHBOARD' };
    } catch {
      return { currentTab: 'DASHBOARD' };
    }
  }, [coachOpen]);

  const handleAcceptSuggestion = (suggestion: any) => {
    const plan = JSON.parse(localStorage.getItem('study_plan') || '[]');
    const [h, m] = (suggestion.start_time as string).split(':').map(Number);
    const endTotalMin = h * 60 + m + (suggestion.duration_minutes || 60);
    const endTime = `${String(Math.floor(endTotalMin / 60) % 24).padStart(2, '0')}:${String(endTotalMin % 60).padStart(2, '0')}`;
    const newEntry: StudyEntry = {
      id: Math.random().toString(36).substr(2, 9),
      day: suggestion.day,
      startTime: suggestion.start_time,
      endTime,
      subject: suggestion.module,
      topic: suggestion.focus_topics.join(', '),
      completed: false,
      isAutoGenerated: true,
      color: 'indigo',
    };
    localStorage.setItem('study_plan', JSON.stringify([...plan, newEntry]));
    toast.success('Im Lernplan eingetragen!');
    onTabChange(ActiveTab.PLANNER);
  };

  /* ── EMPTY STATE ── */
  if (documents.length === 0) {
    return (
      <div className="max-w-[760px] mx-auto px-4 py-12 flex flex-col items-center gap-10 animate-in fade-in duration-700">
        <div className="text-center max-w-md">
          <div
            className="w-[52px] h-[52px] rounded-[16px] flex items-center justify-center mx-auto mb-5"
            style={{ background: 'var(--icon-box)' }}
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
              fill="none" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/>
              <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/>
            </svg>
          </div>
          <h2 className="text-[24px] font-extrabold tracking-tight text-slate-900 dark:text-white mb-2">
            Willkommen bei QuizWise
          </h2>
          <p className="text-[14px] text-slate-500 dark:text-slate-400">
            Lade dein erstes Dokument hoch — in 3 Schritten zum personalisierten Lernkurs.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 w-full">
          {[
            { n: '1', label: 'Dokument hochladen', desc: 'PDF, Word oder Text aus deinem Studium' },
            { n: '2', label: 'Quiz generieren', desc: 'KI erstellt sofort Fragen aus deinen Unterlagen' },
            { n: '3', label: 'Klausur bestehen', desc: 'Lerne gezielt und erziele bessere Noten' },
          ].map(({ n, label, desc }) => (
            <div key={n} className="rounded-[20px] border bg-white dark:bg-slate-900"
              style={{ padding: '20px', borderColor: 'var(--border)' }}>
              <p className="text-[9px] font-black uppercase tracking-widest mb-2"
                style={{ color: 'var(--accent)' }}>Schritt {n}</p>
              <p className="text-sm font-bold text-slate-900 dark:text-white mb-1">{label}</p>
              <p className="text-[11px] text-slate-400">{desc}</p>
            </div>
          ))}
        </div>

        <button
          onClick={() => onTabChange(ActiveTab.LIBRARY)}
          className="flex items-center gap-2 text-white font-black text-[11px] uppercase tracking-widest rounded-[16px] transition-transform hover:scale-[1.02] active:scale-[0.98]"
          style={{ background: 'var(--accent)', padding: '14px 32px' }}
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"
            fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="17 8 12 3 7 8"/>
            <line x1="12" y1="3" x2="12" y2="15"/>
          </svg>
          Erste Quelle hochladen
        </button>
      </div>
    );
  }

  /* ── MAIN DASHBOARD ── */
  return (
    <div className="max-w-[760px] mx-auto px-4 py-6 animate-in fade-in duration-700">

      {/* 1. Begrüßung */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-1">
          <p className="text-[13px] font-semibold text-slate-400">
            Willkommen zurück, {firstName}
          </p>
          {streak.current > 0 && (
            <div
              className="flex items-center gap-1 rounded-full"
              style={{
                padding: '2px 8px',
                background: streak.todayDone
                  ? 'color-mix(in srgb, var(--accent) 12%, transparent)'
                  : 'color-mix(in srgb, #94a3b8 10%, transparent)',
              }}
            >
              <Flame
                size={11}
                style={{ color: streak.todayDone ? 'var(--accent)' : '#94a3b8' }}
                fill={streak.todayDone ? 'var(--accent)' : 'none'}
                strokeWidth={2}
              />
              <span className="text-[11px] font-black"
                style={{ color: streak.todayDone ? 'var(--accent)' : '#94a3b8' }}>
                {streak.current}
              </span>
            </div>
          )}
          {nextExam && (
            <div
              className="flex items-center gap-1 rounded-full"
              style={{
                padding: '2px 8px',
                background: nextExam.days <= 7 ? 'rgba(244,63,94,0.1)' : 'color-mix(in srgb, #94a3b8 10%, transparent)',
              }}
            >
              <Calendar size={11} style={{ color: nextExam.days <= 7 ? '#f43f5e' : '#94a3b8' }} />
              <span className="text-[11px] font-black"
                style={{ color: nextExam.days <= 7 ? '#f43f5e' : '#94a3b8' }}>
                noch {nextExam.days}d
              </span>
            </div>
          )}
        </div>
        <h1 className="text-[26px] font-extrabold tracking-tight text-slate-900 dark:text-white">
          {dueCardsCount > 0
            ? `Du hast heute ${dueCardsCount} Karte${dueCardsCount === 1 ? '' : 'n'} offen`
            : 'Alles erledigt für heute — stark!'}
        </h1>
      </div>

      {/* 2. PRIMARY: fällige Karten */}
      {dueCardsCount > 0 && (
        <button
          onClick={() => onTabChange(ActiveTab.CARDS)}
          className="w-full text-left rounded-[18px] flex items-center justify-between transition-transform hover:scale-[1.01] active:scale-[0.99]"
          style={{ background: 'var(--card-primary)', padding: '24px', marginBottom: '12px' }}
        >
          <div className="flex items-center gap-4">
            <div
              className="w-[46px] h-[46px] rounded-[13px] flex items-center justify-center shrink-0"
              style={{ background: 'var(--accent)' }}
            >
              <Layers size={22} className="text-white" />
            </div>
            <div>
              <p className="text-base font-bold text-white mb-0.5">
                {dueCardsCount} Karte{dueCardsCount === 1 ? '' : 'n'} fällig
              </p>
              <p className="text-[13px] text-slate-400">
                Jetzt wiederholen · ca. {estMinutes} Min
              </p>
            </div>
          </div>
          <span
            className="text-[11px] font-black uppercase tracking-widest text-white rounded-xl shrink-0"
            style={{ background: 'var(--accent)', padding: '10px 16px' }}
          >
            Los geht's
          </span>
        </button>
      )}

      {/* 3. SECONDARY: Weiterlernen */}
      {weiterlernCard && (
        <button
          onClick={() => onTabChange(weiterlernCard.tab)}
          className="w-full text-left rounded-[18px] flex items-center justify-between border bg-white dark:bg-slate-900 transition-colors"
          style={{ borderColor: 'var(--border)', padding: '18px 24px', marginBottom: '28px' }}
        >
          <div className="flex items-center gap-4">
            <div
              className="w-[42px] h-[42px] rounded-xl flex items-center justify-center shrink-0"
              style={{ background: 'var(--accent-soft)' }}
            >
              <Play size={18} style={{ color: 'var(--accent)' }} />
            </div>
            <div>
              <p className="text-[15px] font-bold text-slate-900 dark:text-white mb-0.5">
                Weiterlernen
              </p>
              <p className="text-[13px] text-slate-500 dark:text-slate-400 truncate max-w-[220px]">
                {weiterlernCard.label}
              </p>
            </div>
          </div>
          <ArrowRight size={18} className="text-slate-400 shrink-0" />
        </button>
      )}

      {/* Fallback margin wenn weder primary noch secondary */}
      {dueCardsCount === 0 && !weiterlernCard && <div style={{ height: '28px' }} />}

      {/* 4. LERNMODUS-GRID */}
      <p className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-400 mb-3">
        Lernmodus wählen
      </p>
      <div className="grid grid-cols-3 gap-3" style={{ marginBottom: '28px' }}>
        {MODES.map(({ tab, label, hint, Icon }) => (
          <button
            key={tab}
            onClick={() => onTabChange(tab)}
            className="text-left rounded-2xl border bg-white dark:bg-slate-900 transition-colors"
            style={{ borderColor: 'var(--border)', padding: '18px' }}
          >
            <div
              className="w-[38px] h-[38px] rounded-[11px] flex items-center justify-center"
              style={{ background: 'var(--icon-box)', marginBottom: '14px' }}
            >
              <Icon size={19} className="text-white" />
            </div>
            <p className="text-sm font-bold text-slate-900 dark:text-white mb-1">{label}</p>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-snug">{hint}</p>
          </button>
        ))}
      </div>

      {/* 5. LERN-COACH */}
      <button
        onClick={() => setCoachOpen(true)}
        className="w-full flex items-center justify-between rounded-[18px] border bg-white dark:bg-slate-900 transition-colors"
        style={{ borderColor: 'var(--border)', padding: '18px 24px' }}
      >
        <div className="flex items-center gap-4">
          <div
            className="w-[42px] h-[42px] rounded-xl flex items-center justify-center shrink-0"
            style={{ background: 'var(--icon-box)' }}
          >
            <Bot size={19} className="text-white" />
          </div>
          <div className="text-left">
            <p className="text-[15px] font-bold text-slate-900 dark:text-white mb-0.5">
              Lern-Coach
            </p>
            <p className="text-[13px] text-slate-500 dark:text-slate-400">
              Persönliche Empfehlungen basierend auf deinem Fortschritt
            </p>
          </div>
        </div>
        <ArrowRight size={18} className="text-slate-400 shrink-0" />
      </button>

      {/* KI-Empfehlungen (flowResult) — dezent am Ende */}
      {flowResult && (
        <div style={{ marginTop: '28px' }}>
          <p className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-400 mb-3">
            KI-Empfehlung
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {flowResult.next_actions.map((action, i) => (
              <button
                key={i}
                onClick={() => {
                  const moduleToTab: Record<string, ActiveTab> = {
                    analyse: ActiveTab.RADAR, quiz: ActiveTab.QUIZ,
                    cards: ActiveTab.CARDS, explain: ActiveTab.RECALL,
                    calendar: ActiveTab.PLANNER, exam: ActiveTab.EXAM,
                  };
                  onTabChange(moduleToTab[action.module] ?? ActiveTab.QUIZ);
                }}
                className="text-left rounded-[18px] flex items-start gap-4 border bg-white dark:bg-slate-900 transition-colors"
                style={{ borderColor: 'var(--border)', padding: '18px' }}
              >
                <div
                  className="w-[38px] h-[38px] rounded-[11px] flex items-center justify-center shrink-0"
                  style={{ background: 'var(--accent)', marginTop: '2px' }}
                >
                  <HelpCircle size={18} className="text-white" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-bold text-slate-900 dark:text-white mb-0.5">
                    {action.title}
                  </p>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-snug">
                    {action.why}
                  </p>
                </div>
              </button>
            ))}

            {flowResult.calendar_suggestion?.should_schedule &&
              flowResult.calendar_suggestion.suggested_blocks?.map((block, i) => (
                <div key={i} className="rounded-[18px] flex flex-col gap-3 border bg-white dark:bg-slate-900"
                  style={{ borderColor: 'var(--border)', padding: '18px' }}>
                  <div>
                    <p className="text-[9px] font-black uppercase tracking-widest mb-1"
                      style={{ color: 'var(--accent)' }}>
                      Lernplan-Vorschlag
                    </p>
                    <p className="text-sm font-bold text-slate-900 dark:text-white">
                      {block.day}, {block.start_time} Uhr
                    </p>
                    <p className="text-[11px] text-slate-500 mt-0.5">{block.focus_topics.join(', ')}</p>
                  </div>
                  <button
                    onClick={() => handleAcceptSuggestion(block)}
                    className="w-full rounded-xl text-[10px] font-black uppercase tracking-widest text-white transition-opacity hover:opacity-90"
                    style={{ background: 'var(--accent)', padding: '10px' }}
                  >
                    In Kalender eintragen
                  </button>
                </div>
              ))}
          </div>
        </div>
      )}

      <AgentChat
        agentType="lernCoach"
        context={coachContext}
        isOpen={coachOpen}
        onClose={() => setCoachOpen(false)}
      />
    </div>
  );
};
