
import React, { useState, useMemo } from 'react';
import { ActiveTab, LearningFlowResult, StudyEntry } from '../types';
import { toast } from '../services/toast';
import { Brain, BookOpen, HelpCircle, GraduationCap, Layers, BarChart2, ArrowRight } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const USAGE_KEY = 'quizwise_feature_usage';

function getUsageCounts(): Record<string, number> {
  try { return JSON.parse(localStorage.getItem(USAGE_KEY) || '{}'); }
  catch { return {}; }
}

function trackUsage(id: ActiveTab) {
  const counts = getUsageCounts();
  counts[id] = (counts[id] || 0) + 1;
  localStorage.setItem(USAGE_KEY, JSON.stringify(counts));
}

function getWeekNumber(): number {
  const d = new Date();
  const oneJan = new Date(d.getFullYear(), 0, 1);
  return Math.ceil(((d.getTime() - oneJan.getTime()) / 86400000 + oneJan.getDay() + 1) / 7);
}

function getDateline(): string {
  const days = ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'];
  const months = ['Jan.', 'Feb.', 'März', 'Apr.', 'Mai', 'Juni', 'Juli', 'Aug.', 'Sep.', 'Okt.', 'Nov.', 'Dez.'];
  const d = new Date();
  return `${days[d.getDay()]}, ${d.getDate()}. ${months[d.getMonth()]}`;
}

interface DashboardProps {
  onTabChange: (tab: ActiveTab) => void;
  flowResult: LearningFlowResult | null;
  onAcceptFlow: (res: LearningFlowResult) => void;
}

interface ModuleCard {
  id: ActiveTab;
  num: string;
  title: string;
  kicker: string;
  desc: string;
  icon: LucideIcon;
}

const MODULES: ModuleCard[] = [
  { id: ActiveTab.RECALL,  num: '01', title: 'Recall Studio',  kicker: 'Active Recall',  desc: 'Meistere Themen mit der Feynman-Methode — erkläre, was du weißt.', icon: Brain },
  { id: ActiveTab.LIBRARY, num: '02', title: 'Bibliothek',     kicker: 'Quellenarchiv',  desc: 'Verwalte PDFs und eigene Notizen als durchsuchbares Archiv.', icon: BookOpen },
  { id: ActiveTab.QUIZ,    num: '03', title: 'Quiz Center',    kicker: 'KI-Powered',     desc: 'Aus deinen Quellen generierte Testfragen. Lernen mit Feedback.', icon: HelpCircle },
  { id: ActiveTab.EXAM,    num: '04', title: 'Klausur-Modus',  kicker: 'Prüfungssimulation', desc: 'Zeitgesteuerte Prüfungssimulation mit Nachbesprechung.', icon: GraduationCap },
  { id: ActiveTab.CARDS,   num: '05', title: 'Karteikarten',   kicker: 'Spaced Repetition', desc: 'Anki-inspiriertes Kartentraining mit Selbsteinschätzung.', icon: Layers },
  { id: ActiveTab.RADAR,   num: '06', title: 'Lern-Analyse',   kicker: 'Lückenradar',    desc: 'Finde blinde Flecken und priorisiere deine Lernzeit.', icon: BarChart2 },
];

export const Dashboard: React.FC<DashboardProps> = ({ onTabChange, flowResult }) => {
  const [usageCounts, setUsageCounts] = useState<Record<string, number>>(getUsageCounts);

  const modules = useMemo(() => {
    return [...MODULES].sort((a, b) => (usageCounts[b.id] || 0) - (usageCounts[a.id] || 0));
  }, [usageCounts]);

  const handleCardClick = (id: ActiveTab) => {
    trackUsage(id);
    setUsageCounts(getUsageCounts());
    onTabChange(id);
  };

  const handleAcceptSuggestion = (suggestion: any) => {
    const plan = JSON.parse(localStorage.getItem('study_plan') || '[]');
    const newEntry: StudyEntry = {
      id: Math.random().toString(36).substr(2, 9),
      day: suggestion.day, startTime: suggestion.start_time, endTime: '12:00',
      subject: suggestion.module, topic: suggestion.focus_topics.join(', '),
      completed: false, isAutoGenerated: true, color: 'indigo',
    };
    localStorage.setItem('study_plan', JSON.stringify([...plan, newEntry]));
    toast.success('Im Lernplan eingetragen!');
    onTabChange(ActiveTab.PLANNER);
  };

  const week = getWeekNumber();

  return (
    <div className="animate-in fade-in duration-700" style={{ maxWidth: 860, margin: '0 auto' }}>

      {/* ── Masthead ── */}
      <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 8 }}>
        <div style={{
          fontFamily: 'var(--font-sans)', fontSize: 11, color: 'var(--mute)',
          letterSpacing: '0.22em', textTransform: 'uppercase',
        }}>
          Heute&nbsp;·&nbsp;Woche&nbsp;{week}
        </div>
        <div style={{ display: 'flex', gap: 14, fontFamily: 'var(--font-sans)', fontSize: 12, color: 'var(--mute)' }}>
          <span>SS 26</span><span>·</span><span>{getDateline()}</span>
        </div>
      </div>

      <h1 style={{
        fontFamily: 'var(--font-serif)', fontSize: 'clamp(36px, 6vw, 52px)',
        fontWeight: 500, color: 'var(--ink)', letterSpacing: '-0.015em',
        lineHeight: 1.08, marginBottom: 24,
      }}>
        Heute den Unterschied machen.
      </h1>

      <div style={{ borderTop: '1.5px solid var(--border-color)', marginBottom: 32 }} />

      {/* ── KI-Empfehlung (wenn vorhanden) ── */}
      {flowResult && (
        <div style={{ marginBottom: 40 }}>
          <div style={{
            fontFamily: 'var(--font-sans)', fontSize: 10, color: 'var(--primary)',
            letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: 14,
          }}>
            Nächste Schritte — KI-Empfehlung
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {flowResult.next_actions.map((action, i) => (
              <button key={i}
                onClick={() => onTabChange(action.module.toUpperCase() as ActiveTab)}
                style={{
                  background: 'var(--primary)', color: '#fff', border: 'none',
                  borderRadius: 6, padding: '18px 20px', textAlign: 'left', cursor: 'pointer',
                  transition: 'opacity 0.15s',
                }}
                className="hover:opacity-90 active:scale-[0.98] transition-all"
              >
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'rgba(255,255,255,0.6)', marginBottom: 8 }}>
                  {action.timebox_minutes} Min.
                </div>
                <div style={{ fontFamily: 'var(--font-sans)', fontSize: 15, fontWeight: 600, lineHeight: 1.3, marginBottom: 6 }}>
                  {action.title}
                </div>
                <div style={{ fontFamily: 'var(--font-sans)', fontSize: 12, color: 'rgba(255,255,255,0.7)', fontStyle: 'italic' }}>
                  "{action.why}"
                </div>
              </button>
            ))}

            {flowResult.calendar_suggestion.should_schedule &&
              flowResult.calendar_suggestion.suggested_blocks.map((block, i) => (
                <div key={i} style={{
                  background: 'var(--card)', border: '1px dashed var(--border-color)',
                  borderRadius: 6, padding: '18px 20px',
                }}>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--primary)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                    Lernplan-Vorschlag
                  </div>
                  <div style={{ fontFamily: 'var(--font-sans)', fontSize: 14, fontWeight: 600, color: 'var(--ink)', marginBottom: 4 }}>
                    {block.day}, {block.start_time} Uhr
                  </div>
                  <p style={{ fontSize: 12, color: 'var(--mute)', marginBottom: 14 }}>{block.focus_topics.join(', ')}</p>
                  <button onClick={() => handleAcceptSuggestion(block)} style={{
                    width: '100%', padding: '7px', borderRadius: 4, fontSize: 11,
                    fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-sans)',
                    background: 'var(--primary-soft)', color: 'var(--primary)',
                    border: '1px solid color-mix(in srgb, var(--primary) 25%, transparent)',
                    textTransform: 'uppercase', letterSpacing: '0.1em',
                  }}>
                    In Kalender eintragen
                  </button>
                </div>
              ))
            }
          </div>
          <div style={{ borderTop: '1px solid var(--border-soft)', marginTop: 32, marginBottom: 32 }} />
        </div>
      )}

      {/* ── Module Grid ── */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
        gap: 1,
        border: '1px solid var(--border-color)',
        borderRadius: 4,
        overflow: 'hidden',
      }}>
        {modules.map((mod) => (
          <button key={mod.id} onClick={() => handleCardClick(mod.id)}
            style={{
              background: 'var(--card)', padding: '20px 22px 22px',
              textAlign: 'left', cursor: 'pointer', border: 'none',
              borderBottom: '1px solid var(--border-color)',
              transition: 'background 0.12s',
            }}
            className="group hover:bg-[--p50]"
            onMouseEnter={e => (e.currentTarget.style.background = 'color-mix(in srgb, var(--primary) 5%, var(--card))')}
            onMouseLeave={e => (e.currentTarget.style.background = 'var(--card)')}
          >
            <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 12 }}>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--mute)', letterSpacing: '0.06em' }}>
                {mod.num}
              </span>
              <span style={{ fontFamily: 'var(--font-sans)', fontSize: 10, color: 'var(--mute)', letterSpacing: '0.16em', textTransform: 'uppercase' }}>
                {mod.kicker}
              </span>
            </div>
            <div style={{ fontFamily: 'var(--font-serif)', fontSize: 26, lineHeight: 1.08, color: 'var(--ink)', letterSpacing: '-0.015em', marginBottom: 8 }}>
              {mod.title}
            </div>
            <div style={{ fontFamily: 'var(--font-sans)', fontSize: 13, color: 'var(--ink2)', lineHeight: 1.5 }}>
              {mod.desc}
            </div>
            <div style={{
              display: 'flex', alignItems: 'center', gap: 5, marginTop: 18,
              fontFamily: 'var(--font-sans)', fontSize: 12, color: 'var(--primary)', fontWeight: 500,
            }}>
              Öffnen <ArrowRight style={{ width: 13, height: 13 }} strokeWidth={2} />
            </div>
          </button>
        ))}
      </div>
    </div>
  );
};
