
import React, { useState, useEffect, useMemo } from 'react';
import { StudyEvent, TopicMetric, FlashcardDeck, ExamTerm, Collection, RecurringStudySession, CalendarStudySession } from '../types';
import { GeneratedImage } from './GeneratedImage';
import { CalendarDayPanel } from './CalendarDayPanel';
import { generateSmartStudyPlan } from '../services/geminiService';
import { countDueCards, migrateLegacyCard } from '../services/spacedRepetition';
import { getMistakeQueue } from '../services/mistakeReviewService';
import { getAllResults } from '../services/quizHistoryService';
import { getSpacedSettings, saveSpacedSettings, buildSpacedPlan, applySpacedPlan, buildDueForecast } from '../services/spacedPlanningService';
import { sessionsForDate, applySessionSave, SessionFormInput, fixedWeekdaysFromRecurring, mapSmartPlanToCalendarSessions, migrateStudyEntriesToRecurring, daysUntilDate } from '../services/calendarSessions';
import { toast } from '../services/toast';
import { useTranslation } from '../i18n/I18nProvider';
import { formatDate } from '../i18n/dates';
import { localeTag } from '../i18n';
import type { TKey } from '../i18n';
import { ChevronLeft, ChevronRight, X, Plus, Repeat as RepeatIcon, Clock, CalendarX as CalendarXIcon } from 'lucide-react';

type ViewMode = 'monat' | 'liste';

interface CalendarItem {
  id: string;
  title: string;
  source: 'exam' | 'event' | 'session';
  isAuto?: boolean;
  color?: string;
  recurring?: boolean;
  startTime?: string;
}

interface MonthCell {
  date: Date;
  isCurrentMonth: boolean;
  items: CalendarItem[];
}

const WEEK_DAYS_SHORT = ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'];
/** Index = Date.getDay() (0=So..6=Sa), zum Übersetzen von Wochentag-Indizes über dow.* */
const WEEKDAY_KEYS = ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'];

interface StudyPlannerProps {
  metrics: TopicMetric[];
  decks: FlashcardDeck[];
  examTerms: ExamTerm[];
  onUpdateExams: (terms: ExamTerm[]) => void;
  userId?: string | null;
  collections: Collection[];
  onUpdateCollection: (col: Collection) => void;
}

function toDateStr(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function buildMonthCells(
  year: number, month: number, examTerms: ExamTerm[], events: StudyEvent[],
  recurringSessions: RecurringStudySession[], calendarSessions: CalendarStudySession[], collections: Collection[]
): MonthCell[] {
  const firstDay = new Date(year, month, 1);
  const lastDay = new Date(year, month + 1, 0);

  const startDate = new Date(firstDay);
  const dow = startDate.getDay();
  startDate.setDate(startDate.getDate() - (dow === 0 ? 6 : dow - 1));

  const endDate = new Date(lastDay);
  const endDow = endDate.getDay();
  if (endDow !== 0) endDate.setDate(endDate.getDate() + (7 - endDow));

  const cells: MonthCell[] = [];
  const cur = new Date(startDate);

  while (cur <= endDate) {
    const dateStr = toDateStr(cur);
    const daySessions = sessionsForDate(cur, recurringSessions, calendarSessions, collections);
    const items: CalendarItem[] = [
      ...examTerms.filter(e => e.date === dateStr).map(e => ({ id: e.id, title: e.title, source: 'exam' as const })),
      ...events.filter(ev => ev.date === dateStr).map(ev => ({ id: ev.id, title: ev.title, source: 'event' as const, isAuto: !!ev.isAutoGenerated })),
      ...daySessions.map(s => ({ id: s.id, title: s.topic || s.subjectLabel, source: 'session' as const, color: s.color, recurring: s.recurring, startTime: s.startTime })),
    ];
    cells.push({ date: new Date(cur), isCurrentMonth: cur.getMonth() === month, items });
    cur.setDate(cur.getDate() + 1);
  }

  return cells;
}

export const StudyPlanner: React.FC<StudyPlannerProps> = ({ metrics, decks, examTerms, onUpdateExams, userId, collections, onUpdateCollection }) => {
  const { t, tp } = useTranslation();
  const today = useMemo(() => new Date(), []);
  const todayStr = useMemo(() => toDateStr(today), [today]);

  const [viewMode, setViewMode] = useState<ViewMode>('monat');
  const [calMonth, setCalMonth] = useState(today.getMonth());
  const [calYear, setCalYear] = useState(today.getFullYear());
  const [events, setEvents] = useState<StudyEvent[]>([]);
  const [recurringSessions, setRecurringSessions] = useState<RecurringStudySession[]>([]);
  const [calendarSessions, setCalendarSessions] = useState<CalendarStudySession[]>([]);
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);

  const [isGenerating, setIsGenerating] = useState(false);

  // Forms
  const [showExamForm, setShowExamForm] = useState(false);
  const [newExamTitle, setNewExamTitle] = useState('');
  const [newExamDate, setNewExamDate] = useState('');

  const [showEventForm, setShowEventForm] = useState(false);
  const [newEventTitle, setNewEventTitle] = useState('');
  const [newEventDate, setNewEventDate] = useState('');
  const [newEventType, setNewEventType] = useState<'study' | 'reminder'>('study');
  const [newEventDesc, setNewEventDesc] = useState('');

  // Spaced-Modus (Opt-in): automatische, zeitversetzte Wiederholungs-Sessions
  const [spacedEnabled, setSpacedEnabled] = useState(() => getSpacedSettings().enabled);

  const regenerateSpacedPlan = (
    evs: StudyEvent[],
    recurring: RecurringStudySession[] = recurringSessions,
    calSessions: CalendarStudySession[] = calendarSessions
  ): StudyEvent[] => {
    const plan = buildSpacedPlan({
      decks,
      mistakes: getMistakeQueue(),
      examTerms,
      existingEvents: evs.filter(e => !e.isAutoGenerated),
      recentQuizzes: getAllResults().map(r => ({ docName: r.docName, timestamp: r.timestamp })),
      recurringSessions: recurring,
      calendarSessions: calSessions,
    });
    return applySpacedPlan(evs, plan);
  };

  useEffect(() => {
    // Frisch geparst statt aus dem State gelesen: setRecurringSessions/setCalendarSessions
    // sind an dieser Stelle noch nicht geflusht (React batcht State-Updates), die
    // Regenerierung unten würde sonst mit leeren Arrays rechnen.
    let freshRecurring: RecurringStudySession[] = [];
    let freshCalendarSessions: CalendarStudySession[] = [];
    try { const s = localStorage.getItem('studearc_recurring_sessions'); if (s) freshRecurring = JSON.parse(s); } catch {}
    try { const s = localStorage.getItem('studearc_calendar_sessions'); if (s) freshCalendarSessions = JSON.parse(s); } catch {}

    // Einmalige Migration des entfernten manuellen Wochenplan-Tabs (StudyEntry, wochentag-
    // basiert, localStorage 'study_plan') ins neue datumsechte System — ohne das wären
    // bestehende manuell angelegte Blöcke nach dem Tab-Wegfall unsichtbar verloren.
    if (!localStorage.getItem('studearc_weekplan_migrated_v1')) {
      try {
        const raw = localStorage.getItem('study_plan');
        const oldEntries = raw ? JSON.parse(raw) : [];
        if (Array.isArray(oldEntries) && oldEntries.length > 0) {
          const migrated = migrateStudyEntriesToRecurring(oldEntries, () => Math.random().toString(36).substr(2, 9));
          if (migrated.length > 0) {
            freshRecurring = [...freshRecurring, ...migrated];
            localStorage.setItem('studearc_recurring_sessions', JSON.stringify(freshRecurring));
            if (userId) {
              import('../services/syncService').then(({ syncSavedField }) => syncSavedField(userId, 'recurring_sessions', freshRecurring)).catch(() => {});
            }
          }
        }
      } catch {}
      localStorage.setItem('studearc_weekplan_migrated_v1', 'true');
    }

    setRecurringSessions(freshRecurring);
    setCalendarSessions(freshCalendarSessions);
    let evs: StudyEvent[] = [];
    try { const s = localStorage.getItem('study_events'); if (s) evs = JSON.parse(s); } catch {}
    // Täglicher Refresh: Auto-Plan einmal pro Tag neu berechnen (räumt auch Vergangenes ab)
    const settings = getSpacedSettings();
    if (settings.enabled && settings.lastRunDay !== todayStr) {
      evs = regenerateSpacedPlan(evs, freshRecurring, freshCalendarSessions);
      try { localStorage.setItem('study_events', JSON.stringify(evs)); } catch {}
      saveSpacedSettings({ enabled: true, lastRunDay: todayStr }, userId);
    }
    setEvents(evs);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const saveEvents = (evs: StudyEvent[]) => {
    setEvents(evs);
    try { localStorage.setItem('study_events', JSON.stringify(evs)); } catch {}
    if (userId) {
      import('../services/syncService').then(({ syncSavedField }) => syncSavedField(userId, 'study_events', evs)).catch(() => {});
    }
  };

  const saveRecurringSessions = (list: RecurringStudySession[]) => {
    setRecurringSessions(list);
    try { localStorage.setItem('studearc_recurring_sessions', JSON.stringify(list)); } catch {}
    if (userId) {
      import('../services/syncService').then(({ syncSavedField }) => syncSavedField(userId, 'recurring_sessions', list)).catch(() => {});
    }
  };

  const saveCalendarSessions = (list: CalendarStudySession[]) => {
    setCalendarSessions(list);
    try { localStorage.setItem('studearc_calendar_sessions', JSON.stringify(list)); } catch {}
    if (userId) {
      import('../services/syncService').then(({ syncSavedField }) => syncSavedField(userId, 'calendar_sessions', list)).catch(() => {});
    }
  };

  const handleSaveSession = (input: SessionFormInput) => {
    if (!selectedDate) return;
    const dateStr = toDateStr(selectedDate);
    const weekday = selectedDate.getDay();
    const genId = () => Math.random().toString(36).substr(2, 9);
    const result = applySessionSave(input, dateStr, weekday, recurringSessions, calendarSessions, genId);
    saveRecurringSessions(result.recurring);
    saveCalendarSessions(result.oneOff);
  };

  const handleSkipOccurrence = (ruleId: string, dateStr: string) => {
    saveRecurringSessions(recurringSessions.map(r => r.id === ruleId ? { ...r, skipDates: [...(r.skipDates ?? []), dateStr] } : r));
  };

  const handleDeleteRecurringRule = (ruleId: string) => {
    saveRecurringSessions(recurringSessions.filter(r => r.id !== ruleId));
  };

  const handleDeleteOneOffSession = (id: string) => {
    saveCalendarSessions(calendarSessions.filter(s => s.id !== id));
  };

  const handleUpdateExam = (exam: ExamTerm) => {
    onUpdateExams(examTerms.map(e => (e.id === exam.id ? exam : e)));
  };

  const handleUpdateEvent = (ev: StudyEvent) => {
    saveEvents(events.map(e => (e.id === ev.id ? ev : e)));
  };

  const handleUpdateCollectionColor = (collectionId: string, color: string) => {
    const col = collections.find(c => c.id === collectionId);
    if (col) onUpdateCollection({ ...col, color });
  };

  const handleToggleSpaced = () => {
    if (!spacedEnabled) {
      const next = regenerateSpacedPlan(events);
      const autoCount = next.filter(e => e.isAutoGenerated).length;
      saveEvents(next);
      saveSpacedSettings({ enabled: true, lastRunDay: todayStr }, userId);
      setSpacedEnabled(true);
      toast.success(autoCount > 0
        ? tp('sp2.sessionsPlanned', autoCount)
        : t('sp2.activated'));
    } else {
      const removed = events.filter(e => e.isAutoGenerated).length;
      saveEvents(events.filter(e => !e.isAutoGenerated));
      saveSpacedSettings({ enabled: false, lastRunDay: null }, userId);
      setSpacedEnabled(false);
      toast.info(removed > 0 ? t('sp2.deactivatedN', { n: removed }) : t('sp2.deactivated'));
    }
  };

  const handleRedistribute = () => {
    const next = regenerateSpacedPlan(events);
    saveEvents(next);
    saveSpacedSettings({ enabled: true, lastRunDay: todayStr }, userId);
    toast.success(t('sp2.redistributed', { n: next.filter(e => e.isAutoGenerated).length }));
  };
  const monthCells = useMemo(
    () => buildMonthCells(calYear, calMonth, examTerms, events, recurringSessions, calendarSessions, collections),
    [calYear, calMonth, examTerms, events, recurringSessions, calendarSessions, collections]
  );
  const monthLabel = formatDate(new Date(calYear, calMonth, 1), { month: 'long', year: 'numeric' });

  const goPrev = () => { if (calMonth === 0) { setCalMonth(11); setCalYear(y => y - 1); } else setCalMonth(m => m - 1); };
  const goNext = () => { if (calMonth === 11) { setCalMonth(0); setCalYear(y => y + 1); } else setCalMonth(m => m + 1); };
  const goToday = () => { setCalMonth(today.getMonth()); setCalYear(today.getFullYear()); };

  const SESSION_LIST_HORIZON_DAYS = 30;

  const upcomingItems = useMemo(() => {
    const sessionItems: Array<{
      id: string; title: string; date: string; source: 'session'; description?: string; isAuto: boolean;
      color: string; time: string; recurring: boolean; ruleId?: string;
    }> = [];
    for (let i = 0; i < SESSION_LIST_HORIZON_DAYS; i++) {
      const d = new Date(today.getFullYear(), today.getMonth(), today.getDate() + i);
      for (const s of sessionsForDate(d, recurringSessions, calendarSessions, collections)) {
        sessionItems.push({
          id: s.id,
          title: s.topic || s.subjectLabel,
          date: toDateStr(d),
          source: 'session',
          description: s.topic && s.subjectLabel ? s.subjectLabel : undefined,
          isAuto: false,
          color: s.color,
          time: `${s.startTime}–${s.endTime}`,
          recurring: s.recurring,
          ruleId: s.sourceRuleId,
        });
      }
    }
    return [
      ...examTerms.map(e => ({ id: e.id, title: e.title, date: e.date, source: 'exam' as const, description: undefined as string | undefined, isAuto: false })),
      ...events.map(ev => ({ id: ev.id, title: ev.title, date: ev.date, source: 'event' as const, description: ev.description, isAuto: !!ev.isAutoGenerated })),
      ...sessionItems,
    ]
      .filter(item => item.date >= todayStr)
      .sort((a, b) => a.date.localeCompare(b.date) || ('time' in a ? a.time : '').localeCompare('time' in b ? b.time : ''));
  }, [examTerms, events, todayStr, recurringSessions, calendarSessions, collections, today]);

  const handleSmartPlan = async () => {
    setIsGenerating(true);
    try {
      const fixedSchedule = fixedWeekdaysFromRecurring(recurringSessions, collections);
      const plan = await generateSmartStudyPlan(metrics, decks, examTerms, buildDueForecast(decks, getMistakeQueue(), 7), fixedSchedule);
      const genId = () => Math.random().toString(36).substr(2, 9);
      const mapped = mapSmartPlanToCalendarSessions(plan, today, collections, recurringSessions, genId);
      saveCalendarSessions([...calendarSessions, ...mapped]);
      const days = new Set(mapped.map(s => s.date)).size;
      toast.success(t('sp2.planCreated', { entries: mapped.length, days: tp('sp2.daysN', days) }));
      setViewMode('monat');
    } catch { toast.error(t('sp2.smartPlanFailed')); }
    finally { setIsGenerating(false); }
  };

  const knowledgeGaps = metrics.filter(m => m.confidence < 70);
  const dueDecks = decks.filter(d => countDueCards(d.cards.map(c => c.srs ? c : { ...c, srs: migrateLegacyCard(c) })) > 0);

  return (
    <div className="max-w-6xl mx-auto space-y-10 animate-in fade-in duration-1000 pb-20 px-4">
      {/* Header */}
      <div className="text-center space-y-4">
        <div className="inline-block px-4 py-1.5 bg-indigo-50 dark:bg-indigo-950/30 rounded-full border border-indigo-100 dark:border-indigo-900/50">
          <span className="text-[10px] font-black uppercase tracking-[0.3em] text-indigo-600">{t('sp2.timeManagement')}</span>
        </div>
        <h1 className="text-4xl lg:text-6xl font-black tracking-tighter" style={{ color: 'var(--text-main)' }}>
          {t('sp2.titlePre')} <span style={{ color: 'var(--primary)' }}>{t('sp2.titleAccent')}</span>
        </h1>
        <p className="text-slate-500 dark:text-slate-400 font-medium max-w-xl mx-auto">
          {t('sp2.subtitle')}
        </p>

        <div className="flex justify-center gap-3 pt-2">
          <button
            onClick={handleSmartPlan}
            disabled={isGenerating}
            className="bg-indigo-600 text-white px-8 py-4 rounded-3xl font-black uppercase tracking-[0.2em] text-[11px] shadow-3d-deep hover:scale-105 active:scale-95 transition-all flex items-center gap-2 disabled:opacity-50"
          >
            {isGenerating ? t('sp2.planning') : t('sp2.smartPlan')}
          </button>
          <button
            onClick={() => { setShowExamForm(true); setShowEventForm(false); }}
            className="px-6 py-4 rounded-3xl font-black uppercase tracking-[0.2em] text-[11px] transition-all"
            style={{ background: 'var(--bg-sidebar)', color: 'var(--text-main)', border: '2px solid var(--border-color)' }}
          >
            {t('sp2.addExam')}
          </button>
          <button
            onClick={() => { setShowEventForm(true); setShowExamForm(false); }}
            className="px-6 py-4 rounded-3xl font-black uppercase tracking-[0.2em] text-[11px] transition-all"
            style={{ background: 'var(--bg-sidebar)', color: 'var(--text-main)', border: '2px solid var(--border-color)' }}
          >
            {t('sp2.addEvent')}
          </button>
        </div>

        {/* Spaced-Modus: Opt-in für automatische Wiederholungsplanung */}
        <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
          <button
            onClick={handleToggleSpaced}
            className="flex items-center gap-3 px-5 py-3 rounded-2xl transition-all hover:opacity-90 text-left"
            style={{
              background: spacedEnabled ? 'color-mix(in srgb, var(--primary) 8%, var(--bg-sidebar))' : 'var(--bg-sidebar)',
              border: `1px solid ${spacedEnabled ? 'color-mix(in srgb, var(--primary) 30%, transparent)' : 'var(--border-color)'}`,
            }}
          >
            <div
              className="w-10 h-[22px] rounded-full p-[3px] shrink-0 transition-all"
              style={{ background: spacedEnabled ? 'var(--primary)' : 'var(--border-color)' }}
            >
              <div className={`w-4 h-4 rounded-full bg-white shadow transition-transform ${spacedEnabled ? 'translate-x-[18px]' : ''}`} />
            </div>
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest" style={{ color: spacedEnabled ? 'var(--primary)' : 'var(--text-main)' }}>
                {t('sp2.autoReplanning')}
              </p>
              <p className="text-[9px] font-medium text-slate-400">
                {spacedEnabled ? t('sp2.autoOn') : t('sp2.autoOff')}
              </p>
            </div>
          </button>
          {spacedEnabled && (
            <button
              onClick={handleRedistribute}
              className="px-5 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all hover:scale-105 active:scale-95"
              style={{ background: 'color-mix(in srgb, var(--primary) 12%, transparent)', color: 'var(--primary)', border: '1px solid color-mix(in srgb, var(--primary) 30%, transparent)' }}
            >
              {t('sp2.redistribute')}
            </button>
          )}
        </div>
      </div>

      {/* Widgets */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
        <div className="p-6 rounded-[32px] bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm border border-slate-200/50 dark:border-slate-800/50 hover:bg-white dark:hover:bg-slate-900 transition-all">
          <h3 className="text-[9px] font-black uppercase tracking-[0.4em] text-indigo-500 mb-4">{t('sp2.gaps', { n: knowledgeGaps.length })}</h3>
          <div className="space-y-2">
            {knowledgeGaps.slice(0, 3).map(gap => (
              <div key={gap.id} className="flex justify-between items-center">
                <span className="text-[11px] font-bold text-slate-600 dark:text-slate-300 break-words pr-2">{gap.topic}</span>
                <span className="text-[10px] font-black text-indigo-600">{gap.confidence}%</span>
              </div>
            ))}
            {knowledgeGaps.length === 0 && <p className="text-[10px] text-slate-400 italic">{t('sp2.noGaps')}</p>}
          </div>
        </div>
        <div className="p-6 rounded-[32px] bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm border border-slate-200/50 dark:border-slate-800/50 hover:bg-white dark:hover:bg-slate-900 transition-all">
          <h3 className="text-[9px] font-black uppercase tracking-[0.4em] text-indigo-600 mb-4">{t('sp2.dueCards', { n: dueDecks.length })}</h3>
          <div className="space-y-2">
            {dueDecks.slice(0, 3).map(deck => (
              <div key={deck.id} className="flex justify-between items-center">
                <span className="text-[11px] font-bold text-slate-600 dark:text-slate-300 break-words pr-2">{deck.title}</span>
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-500" />
              </div>
            ))}
            {dueDecks.length === 0 && <p className="text-[10px] text-slate-400 italic">{t('sp2.allLearned')}</p>}
          </div>
        </div>
        <div className="p-6 rounded-[32px] bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm border border-slate-200/50 dark:border-slate-800/50 hover:bg-white dark:hover:bg-slate-900 transition-all">
          <h3 className="text-[9px] font-black uppercase tracking-[0.4em] text-rose-500 mb-4">{t('sp2.exams', { n: examTerms.length })}</h3>
          <div className="space-y-2">
            {examTerms.slice(0, 3).map(exam => (
              <div key={exam.id} className="flex justify-between items-center">
                <span className="text-[11px] font-bold text-slate-600 dark:text-slate-300 break-words pr-2">{exam.title}</span>
                <span className="text-[9px] font-black text-rose-500">{formatDate(exam.date + 'T12:00:00', { day: '2-digit', month: '2-digit' })}</span>
              </div>
            ))}
            {examTerms.length === 0 && <p className="text-[10px] text-slate-400 italic">{t('sp2.noAppointments')}</p>}
          </div>
        </div>
      </div>

      {/* Klausur Form */}
      {showExamForm && (
        <div className="max-w-xl mx-auto p-8 bg-white dark:bg-slate-900 rounded-[32px] border border-slate-200 dark:border-slate-800 shadow-3d-raised animate-in zoom-in-95 duration-200">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-lg font-black dark:text-white">{t('sp2.enterExam')}</h3>
            <button onClick={() => setShowExamForm(false)} className="w-8 h-8 flex items-center justify-center rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-400 hover:text-rose-500 transition-colors"><X size={14} /></button>
          </div>
          <div className="space-y-3">
            <input value={newExamTitle} onChange={e => setNewExamTitle(e.target.value)} placeholder={t('sp2.examTitlePlaceholder')} className="w-full p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl outline-none dark:text-white font-bold text-sm" />
            <input type="date" value={newExamDate} onChange={e => setNewExamDate(e.target.value)} className="w-full p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl outline-none dark:text-white font-bold text-sm" />
            <button onClick={() => {
              if (!newExamTitle || !newExamDate) return;
              onUpdateExams([...examTerms, { id: Math.random().toString(36).substr(2, 5), title: newExamTitle, date: newExamDate, topics: [] }]);
              setNewExamTitle(''); setNewExamDate(''); setShowExamForm(false);
            }} className="w-full bg-rose-500 text-white py-4 rounded-2xl text-[11px] font-black uppercase tracking-widest hover:bg-rose-600 transition-colors">{t('sp2.saveExam')}</button>
          </div>
        </div>
      )}

      {/* Event Form */}
      {showEventForm && (
        <div className="max-w-xl mx-auto p-8 bg-white dark:bg-slate-900 rounded-[32px] border border-slate-200 dark:border-slate-800 shadow-3d-raised animate-in zoom-in-95 duration-200">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-lg font-black dark:text-white">{t('sp2.addAppointment')}</h3>
            <button onClick={() => setShowEventForm(false)} className="w-8 h-8 flex items-center justify-center rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-400 hover:text-rose-500 transition-colors"><X size={14} /></button>
          </div>
          <div className="space-y-3">
            <input value={newEventTitle} onChange={e => setNewEventTitle(e.target.value)} placeholder={t('sp2.eventTitlePlaceholder')} className="w-full p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl outline-none dark:text-white font-bold text-sm" />
            <input type="date" value={newEventDate} onChange={e => setNewEventDate(e.target.value)} className="w-full p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl outline-none dark:text-white font-bold text-sm" />
            <input value={newEventDesc} onChange={e => setNewEventDesc(e.target.value)} placeholder={t('sp2.descPlaceholder')} className="w-full p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl outline-none dark:text-white text-sm" />
            <div className="flex gap-2">
              {(['study', 'reminder'] as const).map(et => (
                <button key={et} onClick={() => setNewEventType(et)} className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${newEventType === et ? 'bg-indigo-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-500'}`}>
                  {et === 'study' ? t('sp2.studyDate') : t('sp2.reminder')}
                </button>
              ))}
            </div>
            <button onClick={() => {
              if (!newEventTitle || !newEventDate) return;
              saveEvents([...events, { id: Math.random().toString(36).substr(2, 9), title: newEventTitle, date: newEventDate, type: newEventType, description: newEventDesc || undefined }]);
              setNewEventTitle(''); setNewEventDate(''); setNewEventDesc(''); setShowEventForm(false);
            }} className="w-full bg-indigo-600 text-white py-4 rounded-2xl text-[11px] font-black uppercase tracking-widest hover:bg-indigo-700 transition-colors">{t('sp2.saveEvent')}</button>
          </div>
        </div>
      )}

      {/* ── View Toggle ── */}
      <div className="max-w-5xl mx-auto">
        <div className="inline-flex bg-slate-100 dark:bg-slate-800/60 rounded-2xl p-1 gap-1">
          {([['monat', t('sp2.month')], ['liste', t('sp2.list')]] as [ViewMode, string][]).map(([mode, label]) => (
            <button
              key={mode}
              onClick={() => setViewMode(mode)}
              className={`px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${viewMode === mode ? 'shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}
              style={viewMode === mode ? { background: 'var(--bg-sidebar)', color: 'var(--text-main)' } : {}}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* ── MONAT VIEW ── */}
      {viewMode === 'monat' && (
        <div className={selectedDate ? 'max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-[1.6fr_1fr] gap-6 items-start' : 'max-w-5xl mx-auto'}>
        <div className="rounded-[32px] shadow-3d-raised overflow-hidden" style={{ background: 'var(--bg-sidebar)', border: '1px solid var(--border-color)' }}>
          {/* Calendar Nav */}
          <div className="flex items-center justify-between px-6 py-5" style={{ borderBottom: '1px solid var(--border-color)' }}>
            <div className="flex items-center gap-3">
              <button aria-label={t('sp.prevMonth')} onClick={goPrev} className="w-9 h-9 flex items-center justify-center rounded-xl transition-colors" style={{ background: 'var(--bg-main)', color: 'var(--border-color)' }}>
                <ChevronLeft size={16} />
              </button>
              <button aria-label={t('sp.nextMonth')} onClick={goNext} className="w-9 h-9 flex items-center justify-center rounded-xl transition-colors" style={{ background: 'var(--bg-main)', color: 'var(--border-color)' }}>
                <ChevronRight size={16} />
              </button>
              <h2 className="text-base font-black capitalize ml-1" style={{ color: 'var(--text-main)' }}>{monthLabel}</h2>
            </div>
            <button onClick={goToday} className="px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-colors" style={{ background: 'var(--bg-main)', color: 'var(--border-color)' }}>
              Heute
            </button>
          </div>

          {/* Weekday headers */}
          <div className="grid grid-cols-7" style={{ borderBottom: '1px solid var(--border-color)' }}>
            {WEEK_DAYS_SHORT.map(d => (
              <div key={d} className="py-3 text-center text-[9px] font-black uppercase tracking-widest text-slate-400">
                {t((`dowShort.${d}`) as TKey)}
              </div>
            ))}
          </div>

          {/* Calendar grid */}
          <div className="grid grid-cols-7">
            {monthCells.map((cell, idx) => {
              const isToday = toDateStr(cell.date) === todayStr;
              const isSelected = !!selectedDate && toDateStr(cell.date) === toDateStr(selectedDate);
              const visible = cell.items.slice(0, 2);
              const overflow = cell.items.length - 2;
              return (
                <button
                  type="button"
                  key={idx}
                  onClick={() => setSelectedDate(cell.date)}
                  className={`min-h-[100px] p-2 text-left transition-colors block w-full ${idx % 7 === 6 ? '' : ''}`}
                  style={{
                    borderBottom: '1px solid var(--border-color)',
                    borderRight: idx % 7 === 6 ? 'none' : '1px solid var(--border-color)',
                    background: isSelected
                      ? 'color-mix(in srgb, var(--primary) 9%, transparent)'
                      : !cell.isCurrentMonth ? 'color-mix(in srgb, var(--bg-main) 60%, var(--bg-sidebar))' : undefined,
                    boxShadow: isSelected ? 'inset 0 0 0 2px var(--primary)' : undefined,
                  }}
                >
                  <span
                    className="inline-flex items-center justify-center w-7 h-7 text-xs font-bold rounded-full mb-1.5 transition-colors"
                    style={isToday
                      ? { background: 'rgb(251,191,36)', color: 'rgb(120,53,15)', fontWeight: 900 }
                      : { color: cell.isCurrentMonth ? 'var(--text-main)' : 'var(--border-color)' }
                    }
                  >
                    {cell.date.getDate()}
                  </span>
                  <div className="space-y-1">
                    {visible.map(item => (
                      <div
                        key={item.id}
                        className={`px-2 py-0.5 rounded-md text-[9px] font-bold break-words flex items-center gap-1 ${
                          item.source === 'exam'
                            ? 'bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-400'
                            : item.source === 'session'
                            ? ''
                            : item.isAuto
                            ? ''
                            : 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400'
                        }`}
                        style={
                          item.source === 'session'
                            ? { background: `color-mix(in srgb, ${item.color} 16%, transparent)`, color: item.color }
                            : item.isAuto
                            ? { background: 'color-mix(in srgb, var(--primary) 12%, transparent)', color: 'var(--primary)' }
                            : undefined
                        }
                      >
                        {item.isAuto && <span className="text-[7px] font-black uppercase tracking-widest opacity-70">{t('sp2.auto')}</span>}
                        {item.source === 'session' && item.recurring && <RepeatIcon size={8} className="shrink-0" />}
                        {item.source === 'session' && item.startTime && <span className="font-mono tabular-nums shrink-0">{item.startTime}</span>}
                        <span className="truncate">{item.title}</span>
                      </div>
                    ))}
                    {overflow > 0 && (
                      <div className="px-2 py-0.5 text-[9px] font-black text-slate-400">
                        {t('sp2.moreN', { n: overflow })}
                      </div>
                    )}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Legend */}
          <div className="flex items-center gap-4 px-6 py-4 flex-wrap" style={{ borderTop: '1px solid var(--border-color)' }}>
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-sm bg-rose-200 dark:bg-rose-900/50" />
              <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t('nav.exam')}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-sm bg-blue-200 dark:bg-blue-900/50" />
              <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t('sp2.legendEvent')}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <RepeatIcon size={11} style={{ color: 'var(--primary)' }} />
              <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t('sp2.sessionLegend')}</span>
            </div>
            {spacedEnabled && (
              <div className="flex items-center gap-1.5">
                <div className="w-3 h-3 rounded-sm" style={{ background: 'color-mix(in srgb, var(--primary) 25%, transparent)' }} />
                <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t('sp2.autoReview')}</span>
              </div>
            )}
            <div className="flex items-center gap-1.5">
              <div className="w-7 h-7 rounded-full bg-amber-400 flex items-center justify-center text-[9px] font-black text-amber-900">{today.getDate()}</div>
              <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t('sp2.today')}</span>
            </div>
          </div>
        </div>

        {selectedDate && (
          <div className="lg:sticky lg:top-6">
            <CalendarDayPanel
              date={selectedDate}
              examsToday={examTerms.filter(e => e.date === toDateStr(selectedDate))}
              eventsToday={events.filter(ev => ev.date === toDateStr(selectedDate))}
              sessions={sessionsForDate(selectedDate, recurringSessions, calendarSessions, collections)}
              collections={collections}
              onUpdateCollectionColor={handleUpdateCollectionColor}
              onUpdateExam={handleUpdateExam}
              onUpdateEvent={handleUpdateEvent}
              onDeleteExam={id => onUpdateExams(examTerms.filter(e => e.id !== id))}
              onDeleteEvent={id => saveEvents(events.filter(ev => ev.id !== id))}
              onDeleteOneOffSession={handleDeleteOneOffSession}
              onSkipRecurringOccurrence={ruleId => handleSkipOccurrence(ruleId, toDateStr(selectedDate))}
              onDeleteRecurringRule={handleDeleteRecurringRule}
              onSaveSession={handleSaveSession}
            />
          </div>
        )}
        </div>
      )}

      {/* ── LISTE VIEW ── */}
      {viewMode === 'liste' && (
        <div className="max-w-5xl mx-auto space-y-3">
          {upcomingItems.length === 0 ? (
            <div className="text-center py-16 text-slate-400">
              <p className="text-[10px] font-black uppercase tracking-widest">{t('sp2.noUpcoming')}</p>
              <p className="text-sm mt-2">{t('sp2.addExamsHint')}</p>
            </div>
          ) : (
            upcomingItems.map(item => {
              const d = new Date(item.date + 'T00:00:00');
              const daysUntil = daysUntilDate(item.date, today);
              const isSession = item.source === 'session';
              const sessionWeekdayName = isSession ? t((`dow.${WEEKDAY_KEYS[d.getDay()]}`) as TKey) : '';
              return (
                <div key={item.id} className={`flex items-center gap-4 px-6 py-5 bg-white dark:bg-slate-900 rounded-[20px] border shadow-sm ${item.source === 'exam' ? 'border-rose-100 dark:border-rose-900/30' : 'border-slate-100 dark:border-slate-800'}`}>
                  <div
                    className={`w-2 h-10 rounded-full shrink-0 ${item.source === 'exam' ? 'bg-rose-400' : isSession ? '' : item.isAuto ? '' : 'bg-blue-400'}`}
                    style={isSession ? { background: item.color } : item.isAuto ? { background: 'var(--primary)' } : undefined}
                  />
                  <div className="flex-grow min-w-0">
                    <p className="text-sm font-black dark:text-white">{item.title}</p>
                    {item.description && <p className="text-xs text-slate-400 mt-0.5 break-words">{item.description}</p>}
                    <p className="text-[9px] font-black uppercase tracking-widest mt-1 flex items-center gap-1.5 flex-wrap" style={isSession ? { color: item.color } : item.isAuto ? { color: 'var(--primary)' } : { color: '#94a3b8' }}>
                      {isSession ? (
                        <>
                          <span className="font-mono tabular-nums normal-case tracking-normal">{item.time}</span>
                          <span className="opacity-50">·</span>
                          {item.recurring ? <RepeatIcon size={9} /> : <Clock size={9} />}
                          {item.recurring ? t('sp2.recurringLabel', { day: sessionWeekdayName }) : t('sp2.onceLabel')}
                        </>
                      ) : item.source === 'exam' ? t('nav.exam') : item.isAuto ? t('sp2.autoReview') : t('sp2.legendEvent')}
                    </p>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-sm font-black dark:text-white">{formatDate(d, { day: '2-digit', month: '2-digit', year: 'numeric' })}</p>
                    <p className={`text-[9px] font-black uppercase tracking-widest mt-0.5 ${daysUntil <= 7 ? 'text-rose-500' : daysUntil <= 14 ? 'text-amber-500' : 'text-slate-400'}`}>
                      {daysUntil === 0 ? t('sp2.today') : daysUntil === 1 ? t('sp2.tomorrow') : t('lc.inDaysN', { n: daysUntil })}
                    </p>
                  </div>
                  {item.source === 'event' && (
                    <button onClick={() => saveEvents(events.filter(ev => ev.id !== item.id))} className="w-7 h-7 shrink-0 flex items-center justify-center rounded-lg text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/20 transition-colors">
                      <X size={12} />
                    </button>
                  )}
                  {isSession && (
                    <button
                      aria-label={item.recurring ? t('sp2.skipOccurrence') : t('common.delete')}
                      title={item.recurring ? t('sp2.skipOccurrence') : t('common.delete')}
                      onClick={() => (item.recurring && item.ruleId ? handleSkipOccurrence(item.ruleId, item.date) : handleDeleteOneOffSession(item.id))}
                      className="w-7 h-7 shrink-0 flex items-center justify-center rounded-lg text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/20 transition-colors"
                    >
                      {item.recurring ? <CalendarXIcon size={12} /> : <X size={12} />}
                    </button>
                  )}
                  {item.source === 'exam' && (
                    <button onClick={() => onUpdateExams(examTerms.filter(e => e.id !== item.id))} className="w-7 h-7 shrink-0 flex items-center justify-center rounded-lg text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/20 transition-colors">
                      <X size={12} />
                    </button>
                  )}
                </div>
              );
            })
          )}
        </div>
      )}
    </div>
  );
};
